spring:
  profiles:
    active: @profiles.active@
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  main:
    allow-circular-references: true
    banner-mode: log
  application:
    name: k3cloud-open-api
  devtools:
    restart:
      enabled: false

logging:
  file:
    path: ../logs/k3colud
  level:
    root: info
    com.e3oms: @logging.level@
    com.kader: @logging.level@
    com.kingdee: @logging.level@
    org.springframework: info
    org.slf4j: warn
    org.apache: warn
    com.microsoft.sqlserver.jdbc: error


