spring:
  config:
    activate:
      on-profile: prod
kingdee:
  k3cloud:
    web-api:
      server-url: http://your-k3cloud-server/k3cloud/
      acct-id: your-acct-id
      user-name: your-user-name
      app-id: your-app-id
      app-sec: your-app-sec
      lc-id: 2052
      org-num: 100
      connect-timeout: 360
      request-timeout: 360
      stock-timeout: 180
      print-execute-url: false
